name = "session-token-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "SESSIONS", id = "eb6ed500a24545908ce73761e91788b7" }
]

routes = [
  { pattern = "meteo.dob-world.com/*", zone_name = "dob-world.com" }
]
